package dev.ddanny165.taskManagement.rest.dto.error;

public enum ErrorType {
    USERNAME_EQUALS_TO_NULL,
    USERNAME_ALREADY_EXISTS,
    INVALID_NULL_PARAMETER,
    NOT_FOUND,
    INVALID_TASK_STATUS_NAME,
    INVALID_TASK_PRIORITY_NAME,
    INVALID_PROJECT_NAME,
    INVALID_TASK_LIST_VISIBILITY
}
